robot:
  follower_ip: "192.168.1.240"
  leader_port: null

  start_joints:
    - 0
    - -90
    - 90
    - -90
    - -90
    - 0
    - 0
  
  camera:
    name: "main"
    width: 640
    height: 480
    fps: 30
    index: 1

# max_seconds: 30.0

dataset:
  episode: 200
  fps: 10
  max_frames: 300
  teleop_hz: 50