defaults:
  - launcher: local
  - solver: cem
  - _self_

world:
  env_name: swm/FrankaPush-v0
  num_envs: ${eval.num_eval}
  max_episode_steps: 50
  history_size: 1
  frame_skip: 1
  env_type: single
  ob_type: pixels
  multiview: False
  width: 64
  height: 64
  visualize_info: False
  terminate_at_goal: True
  config:
    model_path: mujoco_menagerie/franka_emika_panda/scene.xml
    camera_name: top_reverse
    image_size: [64, 64]
    confirm_ik_result: False
    tol: 0.05
    target_sampling_step: 1
    substeps: 200

dataset:
  stats: ${eval.dataset_name}
  keys_to_cache:
    - action
    # - action_joint
    # - action_cartesian
    - qpos
    - qvel
    - bluebox_pos

seed: 42
policy: lewm_weights 

plan_config:
  horizon: 5 #CEMの計算horizon
  receding_horizon: 5
  action_block: 1
  action_space: "joint" #cartesian / joint

eval:

  num_eval: 1 #1
  eval_budget: 200 #50
  img_size: 64
  dataset_name: franka/pairs_100_ep_1_timestep_500_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/push #franka/pairs_1_ep_1_timestep_500_sample_mix_direction_towards_bluebox_1p00_1p00_view_top_reverse/push

  eval_tr_ds:
    execute: false
    goal_offset_steps: 25 #25

  eval_zeroshot:
    execute: true
    num_eval: 1 #1
    # goal_offset_steps: 25 #25
    img_size: 64
    start_positions: [0.50, 0.05, 0.05] #[0.50, 0.07, 0.05]
    goal_positions: [0.50, 0.15, 0.05] #[0.50, 0.15, 0.05]
    init_ee_positions: [0.50, 0.0, 0.05] #[0.50, 0.00, 0.05]


  callables:
    - method: set_state
      args:
        qpos:
          value: qpos
        qvel:
          value: qvel

    - method: set_bluebox_pos
      args:
        bluebox_pos:
          value: bluebox_pos

    - method: set_goal_pos
      args:
        goal_pos:
          value: bluebox_pos
          offset: ${eval.eval_tr_ds.goal_offset_steps}

output:
  filename: franka_push_results.txt